# docker version >= 26.1.1
services:
  webserver:
    image: phpstorm/php-apache:8.3
    restart: always
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www/html
      - ./dist/php.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  mysql-csvimporter:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - MYSQL_CSVIMPORTER:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: csvimporter
      MYSQL_PASSWORD: csvimporterpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "12221:11211"

volumes:
  MYSQL_CSVIMPORTER:
    name: MYSQL_CSVIMPORTER
