# Use root/example as user/password credentials
version: '3.7'

services:
  webserver:
    image: phpstorm/php-apache:8.1-xdebug3.1
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  mysql-csvimporter:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: csvimporter
      MYSQL_PASSWORD: csvimporterpassword
    ports:
      - "3306:3306"
    volumes:
      - MYSQL_CSVIMPORTER:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  MYSQL_CSVIMPORTER:
    name: MYSQL_CSVIMPORTER
